# Official framework image. Look for the different tagged releases at:
# https://hub.docker.com/r/library/node/tags/
image: node:latest

# Pick zero or more services to be used on all builds.
# Only needed when using a docker container to run your tests in.
# Check out: http://docs.gitlab.com/ce/ci/docker/using_docker_images.html#what-is-a-service
services:

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
  - node_modules/
  - functions/node_modules/

test_async:
  script:
   - npm install
   - npm test

staging:
  type: deploy
  script:
   - npm install
   - npm run dev
   - cd functions
   - npm install
   - cd ..
   - ./node_modules/.bin/firebase deploy --token $FIREBASE_TOKEN --non-interactive
  only:
  - master

